from functions import today, tomorrow, after_tomorrow

one = [1, 4, 7, 10, 13, 16, 19, 22, 25, 28]
two = (2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 31)
three = (3, 6, 9, 12, 15, 18, 21, 24, 27, 30)

if today.day in one:
    db2_day_num_one = 'one_1'
    db2_day_num_two = 'one_2'
    db2_day_num_three = 'one_3'
    db2_day_num_four = 'one_4'
    db2_day_num_five = 'one_5'
    db2_day_num_six = 'one_6'
    db2_day_num_seven = 'one_7'
    db2_day_num_eight = 'one_8'
    db2_day_num_nine = 'one_9'
    db2_day_num_ten = 'one_10'
    db2_day_num_eleven = 'one_11'
    db2_day_num_twelve = 'one_12'
if today.day in two:
    db2_day_num_one = 'two_1'
    db2_day_num_two = 'two_2'
    db2_day_num_three = 'two_3'
    db2_day_num_four = 'two_4'
    db2_day_num_five = 'two_5'
    db2_day_num_six = 'two_6'
    db2_day_num_seven = 'two_7'
    db2_day_num_eight = 'two_8'
    db2_day_num_nine = 'two_9'
    db2_day_num_ten = 'two_10'
    db2_day_num_eleven = 'two_11'
    db2_day_num_twelve = 'two_12'
if today.day in three:
    db2_day_num_one = 'three_1'
    db2_day_num_two = 'three_2'
    db2_day_num_three = 'three_3'
    db2_day_num_four = 'three_4'
    db2_day_num_five = 'three_5'
    db2_day_num_six = 'three_6'
    db2_day_num_seven = 'three_7'
    db2_day_num_eight = 'three_8'
    db2_day_num_nine = 'three_9'
    db2_day_num_ten = 'three_10'
    db2_day_num_eleven = 'three_11'
    db2_day_num_twelve = 'three_12'

if tomorrow.day in one:
    db2_day_tomorrow_one = 'one_1'
    db2_day_tomorrow_two = 'one_2'
    db2_day_tomorrow_three = 'one_3'
    db2_day_tomorrow_four = 'one_4'
    db2_day_tomorrow_five = 'one_5'
    db2_day_tomorrow_six = 'one_6'
    db2_day_tomorrow_seven = 'one_7'
    db2_day_tomorrow_eight = 'one_8'
    db2_day_tomorrow_nine = 'one_9'
    db2_day_tomorrow_ten = 'one_10'
    db2_day_tomorrow_eleven = 'one_11'
    db2_day_tomorrow_twelve = 'one_12'
if tomorrow.day in two:
    db2_day_tomorrow_one = 'two_1'
    db2_day_tomorrow_two = 'two_2'
    db2_day_tomorrow_three = 'two_3'
    db2_day_tomorrow_four = 'two_4'
    db2_day_tomorrow_five = 'two_5'
    db2_day_tomorrow_six = 'two_6'
    db2_day_tomorrow_seven = 'two_7'
    db2_day_tomorrow_eight = 'two_8'
    db2_day_tomorrow_nine = 'two_9'
    db2_day_tomorrow_ten = 'two_10'
    db2_day_tomorrow_eleven = 'two_11'
    db2_day_tomorrow_twelve = 'two_12'
if tomorrow.day in three:
    db2_day_tomorrow_one = 'three_1'
    db2_day_tomorrow_two = 'three_2'
    db2_day_tomorrow_three = 'three_3'
    db2_day_tomorrow_four = 'three_4'
    db2_day_tomorrow_five = 'three_5'
    db2_day_tomorrow_six = 'three_6'
    db2_day_tomorrow_seven = 'three_7'
    db2_day_tomorrow_eight = 'three_8'
    db2_day_tomorrow_nine = 'three_9'
    db2_day_tomorrow_ten = 'three_10'
    db2_day_tomorrow_eleven = 'three_11'
    db2_day_tomorrow_twelve = 'three_12'

if after_tomorrow.day in one:
    db2_day_after_tomorrow_one = 'one_1'
    db2_day_after_tomorrow_two = 'one_2'
    db2_day_after_tomorrow_three = 'one_3'
    db2_day_after_tomorrow_four = 'one_4'
    db2_day_after_tomorrow_five = 'one_5'
    db2_day_after_tomorrow_six = 'one_6'
    db2_day_after_tomorrow_seven = 'one_7'
    db2_day_after_tomorrow_eight = 'one_8'
    db2_day_after_tomorrow_nine = 'one_9'
    db2_day_after_tomorrow_ten = 'one_10'
    db2_day_after_tomorrow_eleven = 'one_11'
    db2_day_after_tomorrow_twelve = 'one_12'
if after_tomorrow.day in two:
    db2_day_after_tomorrow_one = 'two_1'
    db2_day_after_tomorrow_two = 'two_2'
    db2_day_after_tomorrow_three = 'two_3'
    db2_day_after_tomorrow_four = 'two_4'
    db2_day_after_tomorrow_five = 'two_5'
    db2_day_after_tomorrow_six = 'two_6'
    db2_day_after_tomorrow_seven = 'two_7'
    db2_day_after_tomorrow_eight = 'two_8'
    db2_day_after_tomorrow_nine = 'two_9'
    db2_day_after_tomorrow_ten = 'two_10'
    db2_day_after_tomorrow_eleven = 'two_11'
    db2_day_after_tomorrow_twelve = 'two_12'
if after_tomorrow.day in three:
    db2_day_after_tomorrow_one = 'three_1'
    db2_day_after_tomorrow_two = 'three_2'
    db2_day_after_tomorrow_three = 'three_3'
    db2_day_after_tomorrow_four = 'three_4'
    db2_day_after_tomorrow_five = 'three_5'
    db2_day_after_tomorrow_six = 'three_6'
    db2_day_after_tomorrow_seven = 'three_7'
    db2_day_after_tomorrow_eight = 'three_8'
    db2_day_after_tomorrow_nine = 'three_9'
    db2_day_after_tomorrow_ten = 'three_10'
    db2_day_after_tomorrow_eleven = 'three_11'
    db2_day_after_tomorrow_twelve = 'three_12'
