from for_telegram.day import today

one = [1, 7, 13, 19, 25]
two = [2, 8, 14, 20, 26]
three = [3, 9, 15, 21, 27]
four = [4, 10, 16, 22, 28]
five = [5, 11, 17, 23, 29]
six = [6, 12, 18, 24, 30]
seven = [31]

if today in one:
    db1_day_num_one = 'one_1'
    db1_day_num_two = 'one_2'
    db1_day_num_three = 'one_3'
    db1_day_num_four = 'one_4'
    db1_day_num_five = 'one_5'
    db1_day_num_six = 'one_6'
    db1_day_num_seven = 'one_7'
    db1_day_num_eight = 'one_8'
    db1_day_num_nine = 'one_9'
    db1_day_num_ten = 'one_10'
    db1_day_num_eleven = 'one_11'
    db1_day_num_twelve = 'one_12'
if today in two:
    db1_day_num_one = 'two_1'
    db1_day_num_two = 'two_2'
    db1_day_num_three = 'two_3'
    db1_day_num_four = 'two_4'
    db1_day_num_five = 'two_5'
    db1_day_num_six = 'two_6'
    db1_day_num_seven = 'two_7'
    db1_day_num_eight = 'two_8'
    db1_day_num_nine = 'two_9'
    db1_day_num_ten = 'two_10'
    db1_day_num_eleven = 'two_11'
    db1_day_num_twelve = 'two_12'
if today in three:
    db1_day_num_one = 'three_1'
    db1_day_num_two = 'three_2'
    db1_day_num_three = 'three_3'
    db1_day_num_four = 'three_4'
    db1_day_num_five = 'three_5'
    db1_day_num_six = 'three_6'
    db1_day_num_seven = 'three_7'
    db1_day_num_eight = 'three_8'
    db1_day_num_nine = 'three_9'
    db1_day_num_ten = 'three_10'
    db1_day_num_eleven = 'three_11'
    db1_day_num_twelve = 'three_12'
if today in four:
    db1_day_num_one = 'four_1'
    db1_day_num_two = 'four_2'
    db1_day_num_three = 'four_3'
    db1_day_num_four = 'four_4'
    db1_day_num_five = 'four_5'
    db1_day_num_six = 'four_6'
    db1_day_num_seven = 'four_7'
    db1_day_num_eight = 'four_8'
    db1_day_num_nine = 'four_9'
    db1_day_num_ten = 'four_10'
    db1_day_num_eleven = 'four_11'
    db1_day_num_twelve = 'four_12'
if today in five:
    db1_day_num_one = 'five_1'
    db1_day_num_two = 'five_2'
    db1_day_num_three = 'five_3'
    db1_day_num_four = 'five_4'
    db1_day_num_five = 'five_5'
    db1_day_num_six = 'five_6'
    db1_day_num_seven = 'five_7'
    db1_day_num_eight = 'five_8'
    db1_day_num_nine = 'five_9'
    db1_day_num_ten = 'five_10'
    db1_day_num_eleven = 'five_11'
    db1_day_num_twelve = 'five_12'
if today in six:
    db1_day_num_one = 'six_1'
    db1_day_num_two = 'six_2'
    db1_day_num_three = 'six_3'
    db1_day_num_four = 'six_4'
    db1_day_num_five = 'six_5'
    db1_day_num_six = 'six_6'
    db1_day_num_seven = 'six_7'
    db1_day_num_eight = 'six_8'
    db1_day_num_nine = 'six_9'
    db1_day_num_ten = 'six_10'
    db1_day_num_eleven = 'six_11'
    db1_day_num_twelve = 'six_12'
if today in seven:
    db1_day_num_one = 'seven_1'
    db1_day_num_two = 'seven_2'
    db1_day_num_three = 'seven_3'
    db1_day_num_four = 'seven_4'
    db1_day_num_five = 'seven_5'
    db1_day_num_six = 'seven_6'
    db1_day_num_seven = 'seven_7'
    db1_day_num_eight = 'seven_8'
    db1_day_num_nine = 'seven_9'
    db1_day_num_ten = 'seven_10'
    db1_day_num_eleven = 'seven_11'
    db1_day_num_twelve = 'seven_12'
